name: Terraform Destroy Workflow

on:
  workflow_dispatch:
    inputs:
      approver:
        description: 'Terraform Destroy Approver'
        required: true
        default: '120269238-myseneca'

jobs:
  confirm:
    runs-on: ubuntu-latest
    outputs:
      is_approved: ${{ steps.check_approval.outputs.approved }}
    steps:
      - name: Check Approver
        id: check_approval
        run: |
          if [ "${{ github.event.inputs.approver }}" == "AuthorizedApproverName" ]; then
            echo "Destroy approved by ${{ github.event.inputs.approver }}"
            echo "::set-output name=approved::true"
          else
            echo "Destroy not approved by ${{ github.event.inputs.approver }}"
            echo "::set-output name=approved::false"
          fi

  terraform_destroy_app:
    needs: confirm
    if: needs.confirm.outputs.is_approved == 'true'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.7.3

      - name: Terraform Init - APP
        run: |
          cd APP/
          terraform init

      - name: Terraform Destroy - APP
        run: |
          cd APP/
          terraform destroy -auto-approve
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_SESSION_TOKEN: ${{ secrets.AWS_SESSION_TOKEN }}
          AWS_REGION: 'us-east-1'

# Add similar jobs for RDS and VPC following the same pattern as terraform_destroy_app
